// ==============================================================================
// LeadPilot AI — In-Memory Demo Dataset for Preview & Serverless Edge Runtimes
// Provides rich, realistic Chennai real estate data when no PostgreSQL DB is connected.
// ==============================================================================

export const DEMO_TEAM_USERS = [
  {
    id: "demo-user-1",
    name: "Suresh Ramanathan",
    email: "suresh@chennaiprimerealty.com",
    phone: "+91 98400 11001",
    role: "OWNER",
    isActive: true,
    createdAt: "2026-01-15T10:00:00.000Z",
    _count: { assignedLeads: 12, assignedFollowUps: 4 },
  },
  {
    id: "demo-user-2",
    name: "Deepa Krishnan",
    email: "deepa@chennaiprimerealty.com",
    phone: "+91 98400 11002",
    role: "ADMIN",
    isActive: true,
    createdAt: "2026-01-15T11:00:00.000Z",
    _count: { assignedLeads: 8, assignedFollowUps: 2 },
  },
  {
    id: "demo-user-3",
    name: "Venkatesh Iyer",
    email: "venkatesh@chennaiprimerealty.com",
    phone: "+91 98400 11003",
    role: "MANAGER",
    isActive: true,
    createdAt: "2026-01-20T09:30:00.000Z",
    _count: { assignedLeads: 14, assignedFollowUps: 5 },
  },
  {
    id: "demo-user-4",
    name: "Karthik Subramanian",
    email: "karthik@chennaiprimerealty.com",
    phone: "+91 98400 11004",
    role: "SALES_USER",
    isActive: true,
    createdAt: "2026-02-01T10:15:00.000Z",
    _count: { assignedLeads: 9, assignedFollowUps: 3 },
  },
  {
    id: "demo-user-5",
    name: "Ananya Sundaram",
    email: "ananya@chennaiprimerealty.com",
    phone: "+91 98400 11005",
    role: "SALES_USER",
    isActive: true,
    createdAt: "2026-02-10T14:20:00.000Z",
    _count: { assignedLeads: 7, assignedFollowUps: 2 },
  },
];

export const DEMO_PROPERTIES = [
  {
    id: "prop-demo-01",
    title: "Radiance Smartville 2BHK",
    description: "Modern gated community apartment near IT corridor with club house, gym, and 24/7 security.",
    location: "OMR, Thoraipakkam",
    city: "Chennai",
    price: 6800000,
    propertyType: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 1120,
    status: "AVAILABLE",
    legalStatus: "VERIFIED_CLEAR_TITLE",
    legalScore: 10,
    legalChecklist: {
      ec30Years: true,
      pattaChitta: true,
      dtcpCmdaApproval: true,
      reraRegistered: true,
      landClassification: true,
      taxReceipts: true,
      unbrokenTitleFlow: true,
      poaVerified: true,
      physicalDemarcation: true,
      advocateClearance: true,
      score: 10,
      status: "VERIFIED_CLEAR_TITLE",
    },
    amenities: ["Swimming Pool", "Gym", "Power Backup", "Covered Car Parking"],
    images: ["/property-placeholder.jpg"],
    createdAt: "2026-02-10T08:00:00.000Z",
  },
  {
    id: "prop-demo-02",
    title: "Casagrand Zenith 3BHK Luxury",
    description: "Spacious luxury flat overlooking green lung space with Italian marble flooring and modular kitchen.",
    location: "Medavakkam",
    city: "Chennai",
    price: 9200000,
    propertyType: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 1540,
    status: "AVAILABLE",
    legalStatus: "VERIFIED_CLEAR_TITLE",
    legalScore: 9,
    legalChecklist: {
      ec30Years: true,
      pattaChitta: true,
      dtcpCmdaApproval: true,
      reraRegistered: true,
      landClassification: true,
      taxReceipts: true,
      unbrokenTitleFlow: true,
      poaVerified: true,
      physicalDemarcation: true,
      advocateClearance: false,
      score: 9,
      status: "MINOR_WARNINGS",
    },
    amenities: ["Clubhouse", "Children Play Area", "24/7 Security", "Jogging Track"],
    images: ["/property-placeholder.jpg"],
    createdAt: "2026-02-12T09:30:00.000Z",
  },
  {
    id: "prop-demo-03",
    title: "Appaswamy Platina 3BHK",
    description: "High-rise executive apartment with breathtaking city view, right beside key tech parks.",
    location: "Porur",
    city: "Chennai",
    price: 11500000,
    propertyType: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 1680,
    status: "AVAILABLE",
    legalStatus: "VERIFIED_CLEAR_TITLE",
    legalScore: 10,
    legalChecklist: {
      ec30Years: true,
      pattaChitta: true,
      dtcpCmdaApproval: true,
      reraRegistered: true,
      landClassification: true,
      taxReceipts: true,
      unbrokenTitleFlow: true,
      poaVerified: true,
      physicalDemarcation: true,
      advocateClearance: true,
      score: 10,
      status: "VERIFIED_CLEAR_TITLE",
    },
    amenities: ["Infinity Pool", "Badminton Court", "EV Charging", "Piped Gas"],
    images: ["/property-placeholder.jpg"],
    createdAt: "2026-02-15T11:00:00.000Z",
  },
  {
    id: "prop-demo-04",
    title: "VGN Fairmont 2BHK Value Home",
    description: "Affordable family home with high rental yield potential, 5 mins from upcoming metro station.",
    location: "Guindy",
    city: "Chennai",
    price: 7800000,
    propertyType: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    status: "AVAILABLE",
    legalStatus: "IN_REVIEW",
    legalScore: 7,
    legalChecklist: {
      ec30Years: true,
      pattaChitta: true,
      dtcpCmdaApproval: true,
      reraRegistered: true,
      landClassification: true,
      taxReceipts: true,
      unbrokenTitleFlow: true,
      poaVerified: false,
      physicalDemarcation: false,
      advocateClearance: false,
      score: 7,
      status: "IN_REVIEW",
    },
    amenities: ["Gym", "Rainwater Harvesting", "Lift", "Security"],
    images: ["/property-placeholder.jpg"],
    createdAt: "2026-02-18T14:10:00.000Z",
  },
  {
    id: "prop-demo-05",
    title: "Olympia Opaline Sea View 3BHK",
    description: "Breathtaking panoramic sea views from the 14th floor, world-class amenities and private clubhouse.",
    location: "Navalur, OMR",
    city: "Chennai",
    price: 14500000,
    propertyType: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 1890,
    status: "AVAILABLE",
    legalStatus: "VERIFIED_CLEAR_TITLE",
    legalScore: 10,
    legalChecklist: {
      ec30Years: true,
      pattaChitta: true,
      dtcpCmdaApproval: true,
      reraRegistered: true,
      landClassification: true,
      taxReceipts: true,
      unbrokenTitleFlow: true,
      poaVerified: true,
      physicalDemarcation: true,
      advocateClearance: true,
      score: 10,
      status: "VERIFIED_CLEAR_TITLE",
    },
    amenities: ["Sea View", "Clubhouse", "Squash Court", "Restaurant"],
    images: ["/property-placeholder.jpg"],
    createdAt: "2026-02-20T16:45:00.000Z",
  },
  {
    id: "prop-demo-06",
    title: "ECR Beachfront Luxury Villa",
    description: "Palatial 4BHK villa 200 meters from golden sandy beach, private plunge pool and party deck.",
    location: "ECR, Palavakkam",
    city: "Chennai",
    price: 38000000,
    propertyType: "Villa",
    bedrooms: 4,
    bathrooms: 5,
    area: 3600,
    status: "AVAILABLE",
    legalStatus: "VERIFIED_CLEAR_TITLE",
    legalScore: 10,
    legalChecklist: {
      ec30Years: true,
      pattaChitta: true,
      dtcpCmdaApproval: true,
      reraRegistered: true,
      landClassification: true,
      taxReceipts: true,
      unbrokenTitleFlow: true,
      poaVerified: true,
      physicalDemarcation: true,
      advocateClearance: true,
      score: 10,
      status: "VERIFIED_CLEAR_TITLE",
    },
    amenities: ["Private Pool", "Beach Access", "Servant Quarters", "Home Automation"],
    images: ["/property-placeholder.jpg"],
    createdAt: "2026-02-25T12:00:00.000Z",
  },
  {
    id: "prop-demo-07",
    title: "Anna Nagar Tower View 3BHK",
    description: "Prestigious address in prime Anna Nagar Western Extension, walking distance from metro.",
    location: "Anna Nagar",
    city: "Chennai",
    price: 24000000,
    propertyType: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: 1780,
    status: "AVAILABLE",
    legalStatus: "VERIFIED_CLEAR_TITLE",
    legalScore: 10,
    legalChecklist: {
      ec30Years: true,
      pattaChitta: true,
      dtcpCmdaApproval: true,
      reraRegistered: true,
      landClassification: true,
      taxReceipts: true,
      unbrokenTitleFlow: true,
      poaVerified: true,
      physicalDemarcation: true,
      advocateClearance: true,
      score: 10,
      status: "VERIFIED_CLEAR_TITLE",
    },
    amenities: ["Gym", "Intercom", "2 Car Parks", "Rooftop Party Area"],
    images: ["/property-placeholder.jpg"],
    createdAt: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "prop-demo-08",
    title: "Tambaram Grandeur 2BHK",
    description: "Ready-to-move 2BHK near MEPZ and Hindu Mission Hospital with zero GST.",
    location: "Tambaram East",
    city: "Chennai",
    price: 6400000,
    propertyType: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 1080,
    status: "AVAILABLE",
    legalStatus: "VERIFIED_CLEAR_TITLE",
    legalScore: 10,
    legalChecklist: {
      ec30Years: true,
      pattaChitta: true,
      dtcpCmdaApproval: true,
      reraRegistered: true,
      landClassification: true,
      taxReceipts: true,
      unbrokenTitleFlow: true,
      poaVerified: true,
      physicalDemarcation: true,
      advocateClearance: true,
      score: 10,
      status: "VERIFIED_CLEAR_TITLE",
    },
    amenities: ["Lift", "Power Backup", "Solar Water Heating"],
    images: ["/property-placeholder.jpg"],
    createdAt: "2026-03-05T15:30:00.000Z",
  },
];

export const DEMO_LEADS = [
  {
    id: "lead-demo-01",
    name: "Rajesh Kannan",
    phone: "+91 98401 23456",
    email: "rajesh.k@gmail.com",
    source: "WHATSAPP",
    status: "QUALIFIED",
    priority: "HIGH",
    leadScore: 88,
    requirement: "I need a 2BHK near Tambaram under 70 lakhs, ready to move.",
    location: "Tambaram",
    budgetMin: 5500000,
    budgetMax: 7000000,
    propertyType: "Apartment",
    bedrooms: 2,
    urgency: "HIGH",
    leadClassification: "GENUINE_BUYER",
    classificationReason: "Direct end-buyer looking for immediate inspection with loan pre-approval.",
    assignedUser: DEMO_TEAM_USERS[3], // Karthik
    aiAnalysis: {
      leadScore: 88,
      summary: "High intent homebuyer seeking ready-to-move 2BHK apartment in Tambaram under ₹70L.",
      intent: "Immediate purchase for self-occupation with bank loan pre-approved.",
    },
    createdAt: "2026-03-10T09:15:00.000Z",
  },
  {
    id: "lead-demo-02",
    name: "Priya Sundaram",
    phone: "+91 98402 34567",
    email: "priya.s@outlook.com",
    source: "WEBSITE",
    status: "SITE_VISIT",
    priority: "HIGH",
    leadScore: 76,
    requirement: "Looking for 2 or 3BHK flat on OMR near TCS office, budget 85L.",
    location: "OMR, Thoraipakkam",
    budgetMin: 7000000,
    budgetMax: 8500000,
    propertyType: "Apartment",
    bedrooms: 3,
    urgency: "MEDIUM",
    leadClassification: "GENUINE_BUYER",
    classificationReason: "IT professional buying first residential home near workplace.",
    assignedUser: DEMO_TEAM_USERS[4], // Ananya
    aiAnalysis: {
      leadScore: 76,
      summary: "Senior IT consultant interested in OMR flats near Thoraipakkam.",
      intent: "Self-use residential purchase; site visit scheduled for this weekend.",
    },
    createdAt: "2026-03-11T11:45:00.000Z",
  },
  {
    id: "lead-demo-03",
    name: "Kumaravel Murugan",
    phone: "+91 98403 45678",
    email: "kumaravel.m@yahoo.com",
    source: "FACEBOOK",
    status: "SITE_VISIT",
    priority: "HIGH",
    leadScore: 84,
    requirement: "Need a residential apartment in Velachery near railway station under 1.1 Crore.",
    location: "Velachery",
    budgetMin: 9000000,
    budgetMax: 11000000,
    propertyType: "Apartment",
    bedrooms: 3,
    urgency: "HIGH",
    leadClassification: "GENUINE_BUYER",
    classificationReason: "Family seeking proximity to railway station and schools.",
    assignedUser: DEMO_TEAM_USERS[2], // Venkatesh
    aiAnalysis: {
      leadScore: 84,
      summary: "3BHK requirement in Velachery with ₹1.1 Cr budget.",
      intent: "Active buyer actively comparing projects.",
    },
    createdAt: "2026-03-12T14:20:00.000Z",
  },
  {
    id: "lead-demo-04",
    name: "Ananya Narayanan",
    phone: "+91 98404 56789",
    email: "ananya.n@gmail.com",
    source: "PHONE",
    status: "NEGOTIATION",
    priority: "HIGH",
    leadScore: 92,
    requirement: "Looking for an independent villa on ECR close to beach. Budget 3.5 to 4 Cr.",
    location: "ECR, Palavakkam",
    budgetMin: 35000000,
    budgetMax: 40000000,
    propertyType: "Villa",
    bedrooms: 4,
    urgency: "HIGH",
    leadClassification: "GENUINE_BUYER",
    classificationReason: "High Net Worth Individual (HNI) seeking luxury sea-facing villa on ECR.",
    assignedUser: DEMO_TEAM_USERS[0], // Suresh (Owner)
    aiAnalysis: {
      leadScore: 92,
      summary: "High-value luxury villa buyer on ECR. Completed 2 site inspections.",
      intent: "Price negotiation in final stage with developer.",
    },
    createdAt: "2026-03-13T10:00:00.000Z",
  },
  {
    id: "lead-demo-05",
    name: "Arun Swaminathan",
    phone: "+91 98405 67890",
    email: "arun.swami@gmail.com",
    source: "GOOGLE_FORM",
    status: "QUALIFIED",
    priority: "HIGH",
    leadScore: 78,
    requirement: "Looking for 3BHK in Anna Nagar, budget 2.2 Cr. Need good school proximity.",
    location: "Anna Nagar",
    budgetMin: 18000000,
    budgetMax: 22000000,
    propertyType: "Apartment",
    bedrooms: 3,
    urgency: "MEDIUM",
    leadClassification: "GENUINE_BUYER",
    classificationReason: "Family upgrading to prime central Chennai location.",
    assignedUser: DEMO_TEAM_USERS[2], // Venkatesh
    aiAnalysis: {
      leadScore: 78,
      summary: "Upmarket buyer searching Anna Nagar Tower vicinity.",
      intent: "Qualified with high financial readiness.",
    },
    createdAt: "2026-03-14T16:10:00.000Z",
  },
  {
    id: "lead-demo-06",
    name: "Divya Balaji",
    phone: "+91 98406 78901",
    email: "divya.balaji@hotmail.com",
    source: "WHATSAPP",
    status: "CONTACTED",
    priority: "MEDIUM",
    leadScore: 68,
    requirement: "Want 2BHK gated community flat under 60 lakhs with loan assistance.",
    location: "Medavakkam",
    budgetMin: 4500000,
    budgetMax: 6000000,
    propertyType: "Apartment",
    bedrooms: 2,
    urgency: "MEDIUM",
    leadClassification: "GENUINE_BUYER",
    classificationReason: "First-time homebuyer inquiring through automated WhatsApp bot.",
    assignedUser: DEMO_TEAM_USERS[3], // Karthik
    aiAnalysis: {
      leadScore: 68,
      summary: "First-time home buyer requesting loan assistance in Medavakkam.",
      intent: "Need preliminary brochure and bank EMI calculations.",
    },
    createdAt: "2026-03-15T12:30:00.000Z",
  },
  {
    id: "lead-demo-07",
    name: "Siddharth Chandran",
    phone: "+91 98407 89012",
    email: "sid.chandran@gmail.com",
    source: "WEBSITE",
    status: "CONVERTED",
    priority: "HIGH",
    leadScore: 96,
    requirement: "3BHK near DLF IT park, budget 1.15 Cr, possession within 6 months.",
    location: "Porur",
    budgetMin: 10000000,
    budgetMax: 11500000,
    propertyType: "Apartment",
    bedrooms: 3,
    urgency: "HIGH",
    leadClassification: "GENUINE_BUYER",
    classificationReason: "Closed deal on Appaswamy Platina 3BHK unit.",
    assignedUser: DEMO_TEAM_USERS[0], // Suresh
    aiAnalysis: {
      leadScore: 96,
      summary: "Agreement signed, booking token received.",
      intent: "Deal Converted & Token registered.",
    },
    createdAt: "2026-03-16T15:00:00.000Z",
  },
  {
    id: "lead-demo-08",
    name: "Lakshmi Narayanan",
    phone: "+91 98408 90123",
    email: "lakshmi.n@gmail.com",
    source: "MANUAL",
    status: "FOLLOW_UP",
    priority: "HIGH",
    leadScore: 74,
    requirement: "Looking for high-end luxury apartment in Adyar or Besant Nagar. Budget 2.5 Cr.",
    location: "Adyar",
    budgetMin: 20000000,
    budgetMax: 25000000,
    propertyType: "Apartment",
    bedrooms: 3,
    urgency: "MEDIUM",
    leadClassification: "GENUINE_BUYER",
    classificationReason: "Direct referral looking for central residential apartment.",
    assignedUser: DEMO_TEAM_USERS[4], // Ananya
    aiAnalysis: {
      leadScore: 74,
      summary: "Luxury buyer for south Chennai central localities.",
      intent: "Follow-up call due regarding floor plans.",
    },
    createdAt: "2026-03-17T09:00:00.000Z",
  },
  {
    id: "lead-demo-09",
    name: "Gautham Ramakrishnan",
    phone: "+91 98409 01234",
    email: "gautham.r@gmail.com",
    source: "INSTAGRAM",
    status: "NEW",
    priority: "LOW",
    leadScore: 55,
    requirement: "Need 2BHK or 3BHK near Vivira Mall, budget around 75L.",
    location: "Navalur",
    budgetMin: 6000000,
    budgetMax: 7500000,
    propertyType: "Apartment",
    bedrooms: 2,
    urgency: "LOW",
    leadClassification: "CASUAL_INQUIRY",
    classificationReason: "Initial top-of-funnel lead from Instagram Reel campaign.",
    assignedUser: DEMO_TEAM_USERS[3], // Karthik
    aiAnalysis: {
      leadScore: 55,
      summary: "Inquired via social media. Needs qualifying phone call.",
      intent: "Researching options for late 2026 possession.",
    },
    createdAt: "2026-03-18T18:25:00.000Z",
  },
  {
    id: "lead-demo-10",
    name: "Meera Krishnaswamy",
    phone: "+91 98410 12345",
    email: "meera.k@gmail.com",
    source: "WEBSITE",
    status: "QUALIFIED",
    priority: "HIGH",
    leadScore: 82,
    requirement: "Looking for 2BHK flat near Kathipara junction with power backup. Budget 80L.",
    location: "Guindy",
    budgetMin: 6500000,
    budgetMax: 8000000,
    propertyType: "Apartment",
    bedrooms: 2,
    urgency: "HIGH",
    leadClassification: "GENUINE_BUYER",
    classificationReason: "Buyer needing central connectivity to airport and metro.",
    assignedUser: DEMO_TEAM_USERS[2], // Venkatesh
    aiAnalysis: {
      leadScore: 82,
      summary: "Guindy 2BHK requirement with strict delivery timeline.",
      intent: "Ready to inspect VGN Fairmont.",
    },
    createdAt: "2026-03-19T10:40:00.000Z",
  },
];

export const DEMO_FOLLOWUPS = [
  {
    id: "fup-demo-01",
    type: "CALL",
    status: "PENDING",
    scheduledAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(), // 2h from now (Today)
    message: "Call Rajesh to confirm Saturday 11 AM site visit for Radiance Smartville 2BHK.",
    lead: {
      id: "lead-demo-01",
      name: "Rajesh Kannan",
      phone: "+91 98401 23456",
      leadScore: 88,
      status: "QUALIFIED",
      location: "Tambaram",
    },
    assignedUser: DEMO_TEAM_USERS[3],
  },
  {
    id: "fup-demo-02",
    type: "WHATSAPP",
    status: "PENDING",
    scheduledAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(), // 4h from now (Today)
    message: "Share Casagrand Zenith 3BHK brochure & cost sheet via WhatsApp.",
    lead: {
      id: "lead-demo-02",
      name: "Priya Sundaram",
      phone: "+91 98402 34567",
      leadScore: 76,
      status: "SITE_VISIT",
      location: "OMR, Thoraipakkam",
    },
    assignedUser: DEMO_TEAM_USERS[4],
  },
  {
    id: "fup-demo-03",
    type: "CALL",
    status: "PENDING",
    scheduledAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(), // Yesterday (Overdue)
    message: "Overdue call: Check with Arun regarding bank sanction letter for Anna Nagar apartment.",
    lead: {
      id: "lead-demo-05",
      name: "Arun Swaminathan",
      phone: "+91 98405 67890",
      leadScore: 78,
      status: "QUALIFIED",
      location: "Anna Nagar",
    },
    assignedUser: DEMO_TEAM_USERS[2],
  },
  {
    id: "fup-demo-04",
    type: "CALL",
    status: "PENDING",
    scheduledAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(), // 2 days later (Upcoming)
    message: "Follow-up after ECR Villa site walkthrough with spouse.",
    lead: {
      id: "lead-demo-04",
      name: "Ananya Narayanan",
      phone: "+91 98404 56789",
      leadScore: 92,
      status: "NEGOTIATION",
      location: "ECR, Palavakkam",
    },
    assignedUser: DEMO_TEAM_USERS[0],
  },
];

